/**
 * Copie de secours du référentiel BTP (alignée sur la migration SQL Supabase).
 * Utilisée si la base est vide ou injoignable.
 */
import type { BtpMetier } from "./btp-referentiel-types";

type SeedSousActiviteRow = { id: string; label: string };

export const SEED_BTP_METIERS: BtpMetier[] = [
  { id: "plomberie", label: "Plomberie & chauffage", codeNaf: "43.22A,43.22B" },
  { id: "electricite", label: "Électricité (installations)", codeNaf: "43.21A" },
  { id: "maconnerie", label: "Maçonnerie & gros œuvre", codeNaf: "43.99A" },
  { id: "menuiserie", label: "Menuiserie, bois & PVC", codeNaf: "43.32A" },
  { id: "peinture", label: "Peinture & vitrerie", codeNaf: "43.34Z" },
  { id: "carrelage", label: "Carrelage & revêtements sols/murs", codeNaf: "43.33Z" },
  { id: "platrerie", label: "Plâtrerie & plaques de plâtre", codeNaf: "43.31Z" },
  { id: "couverture", label: "Couverture & étanchéité toiture", codeNaf: "43.91A,43.91B" },
  { id: "demolition", label: "Démolition & terrassement", codeNaf: "43.11Z,43.12A,43.12B" },
  { id: "autres-btp", label: "Autres travaux spécialisés BTP", codeNaf: "43.99C" },
];

export const SEED_BTP_SOUS_ACTIVITES: Record<string, SeedSousActiviteRow[]> = {
  plomberie: [
    { id: "sd-bain-complete", label: "Salle de bain complète (création / rénovation)" },
    { id: "douche-baignoire", label: "Douche, baignoire, receveur, paroi" },
    { id: "wc-suspendu-broyeur", label: "WC, WC suspendu, broyeur sanitaire" },
    { id: "evier-lave-vaisselle", label: "Évier cuisine, lave-vaisselle, raccordements" },
    { id: "robinetterie", label: "Robinetterie (remplacement, mitigeur, mélangeur)" },
    { id: "fuites-recherche", label: "Fuites — recherche et réparation" },
    { id: "canalisation-engorgee", label: "Canalisations engorgées / débouchage" },
    { id: "ballon-ecs", label: "Ballon d’eau chaude, cumulus, surcumulateur" },
    { id: "chauffage-emitters", label: "Radiateurs, sèche-serviettes, robinets thermostatiques" },
    { id: "plan-chauffage-pac", label: "Raccordements pompe à chaleur / plancher chauffant (hydraulique)" },
    { id: "adoucisseur-filtre", label: "Adoucisseur, filtration, traitement d’eau" },
    { id: "vmc-piquage", label: "Piquages VMC / extracteurs (eau usées liées à l’équipement)" },
  ],
  electricite: [
    { id: "mise-normes-tableau", label: "Mise aux normes du tableau électrique" },
    { id: "nouveau-tableau", label: "Nouveau tableau / réagencement des circuits" },
    { id: "prises-interrupteurs", label: "Prises, interrupteurs, points lumineux" },
    { id: "eclairage-encastre", label: "Spots, rails, éclairage LED intérieur / extérieur" },
    { id: "depannage-pannes", label: "Dépannage, recherche de panne" },
    { id: "installation-neuf", label: "Installation neuve (logement, extension)" },
    { id: "renovation-secondaire", label: "Rénovation tertiaire / locaux pros" },
    { id: "domotique", label: "Domotique, volets roulants électriques, programmation" },
    { id: "borne-recharge", label: "Borne de recharge véhicule électrique" },
    { id: "mise-terre-liaison", label: "Mise à la terre, liaisons équipotentielles" },
    { id: "courant-faible", label: "Courant faible (RJ45, antenne, interphone basique)" },
  ],
  maconnerie: [
    { id: "extension-gros-oeuvre", label: "Extension, surélévation — gros œuvre" },
    { id: "murs-clotures", label: "Murs, clôtures, murets, soubassements" },
    { id: "ouvertures-baies", label: "Ouverture / création de baies, linteaux" },
    { id: "dalle-chape", label: "Dalle béton, chape" },
    { id: "terrasse-exterieure", label: "Terrasse portée, plots, maçonnerie extérieure" },
    { id: "reprises-fissures", label: "Reprises de fissures, scellements" },
    { id: "enduits-facade", label: "Enduits façade / reprises maçonnage" },
    { id: "escaliers-beton", label: "Escaliers béton, rampes d’accès" },
  ],
  menuiserie: [
    { id: "fenetres-pvc-bois-alu", label: "Fenêtres PVC, bois, alu — pose / remplacement" },
    { id: "portes-entree", label: "Portes d’entrée, portes blindées" },
    { id: "portes-interieures", label: "Portes intérieures, portes coulissantes" },
    { id: "volets", label: "Volets roulants, battants, persiennes" },
    { id: "garde-corps", label: "Garde-corps, tringles rideaux intégrées (menuiserie)" },
    { id: "cuisine-meuble", label: "Pose cuisine équipée (meubles, plans de travail bois)" },
    { id: "placards-dressing", label: "Placards, dressings sur mesure" },
    { id: "parquet-stratifie", label: "Parquet, stratifié, lame PVC clipsée" },
    { id: "lambourdes-ossature-bois", label: "Ossature bois légère, lambourdes (hors charpente lourde)" },
  ],
  peinture: [
    { id: "peinture-interieure", label: "Peinture intérieure murs / plafonds / boiseries" },
    { id: "peinture-facade", label: "Peinture façade, ravalement léger" },
    { id: "vitrerie-simple", label: "Vitrerie simple (petits carreaux, doubles vitrages accessibles)" },
    { id: "papier-peint-toile", label: "Papier peint, toile de verre, revêtements muraux" },
    { id: "preparation-supports", label: "Préparation des supports (rebouchage, ponçage)" },
    { id: "laques-batiments", label: "Laques, peintures sols (locaux secs)" },
  ],
  carrelage: [
    { id: "carrelage-sdb", label: "Carrelage salle de bain, douche à l’italienne" },
    { id: "carrelage-cuisine", label: "Carrelage cuisine, crédence" },
    { id: "carrelage-sol-sejour", label: "Carrelage sol séjour, entrée, couloir" },
    { id: "carrelage-exterieur", label: "Carrelage / grès cérame extérieur, terrasse" },
    { id: "mosaique-faience", label: "Faïence, mosaïque, bordures" },
    { id: "chape-ragreage", label: "Chape, ragréage avant pose" },
    { id: "joints-hydrofuge", label: "Joints hydrofuges, traitement des angles" },
  ],
  platrerie: [
    { id: "cloisons-ba13", label: "Cloisons en plaques de plâtre (BA13)" },
    { id: "doublages-isolation", label: "Doublages collés / sur ossature + isolation" },
    { id: "faux-plafonds", label: "Faux plafonds suspendus, dalles acoustiques" },
    { id: "enduits-lisses", label: "Enduits lissés, bandes à joints" },
    { id: "trous-ouvertures", label: "Reprises après ouvertures, trous, saignées" },
    { id: "corniches-decor", label: "Corniches, éléments décoratifs plâtre / staff (léger)" },
  ],
  couverture: [
    { id: "tuiles-ardoises", label: "Tuiles, ardoises — pose et réparation" },
    { id: "etancheite-toiture", label: "Étanchéité toiture-terrasse, relevés" },
    { id: "zinguerie", label: "Zinguerie, gouttières, chéneaux, descentes" },
    { id: "velux-fenetres-toit", label: "Fenêtres de toit, Velux — entourage" },
    { id: "isolation-combles", label: "Isolation de combles (soufflage, rouleaux, panneaux)" },
    { id: "demoussage-hydrofuge", label: "Démoussage, traitement hydrofuge toiture" },
    { id: "charpente-legere-reparation", label: "Petites réparations charpente accessible (liteaux, voliges)" },
  ],
  demolition: [
    { id: "demolition-maison", label: "Démolition maison / bâtiment léger" },
    { id: "demolition-interieure", label: "Dépose cloisons, sanitaires, cuisines" },
    { id: "terrassement-tranchee", label: "Terrassement, tranchées, fouilles" },
    { id: "evacuation-dechets", label: "Évacuation gravats, bennes, tri" },
    { id: "curage-locaux", label: "Curage de locaux, débarras chantier" },
    { id: "sciage-carottage", label: "Sciage, carottage (accès sous-traitance possible)" },
  ],
  "autres-btp": [
    { id: "second-oeuvre-divers", label: "Second œuvre divers (pose accessoires, petits travaux)" },
    { id: "etancheite-sou-sol", label: "Étanchéité sous-sol, cuvelage léger" },
    { id: "isolation-acoustique", label: "Isolation acoustique ponctuelle (complément)" },
    { id: "nettoyage-haute-pression", label: "Nettoyage façade / toiture haute pression" },
    { id: "autre-sur-devis", label: "Autre — précisé au devis" },
  ],
};
