-- Référentiel « type d’artisan » + prestations précises (source unique Supabase).
-- Exécuter dans Supabase → SQL Editor.

CREATE TABLE "BtpMetier" (
    "id" TEXT NOT NULL,
    "label" TEXT NOT NULL,
    "codeNaf" TEXT NOT NULL,
    "sortOrder" INTEGER NOT NULL DEFAULT 0,

    CONSTRAINT "BtpMetier_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "BtpPrestation" (
    "id" TEXT NOT NULL,
    "metierId" TEXT NOT NULL,
    "label" TEXT NOT NULL,
    "pricedBySurface" BOOLEAN NOT NULL DEFAULT false,
    "sortOrder" INTEGER NOT NULL DEFAULT 0,

    CONSTRAINT "BtpPrestation_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "BtpPrestation_metierId_fkey" FOREIGN KEY ("metierId") REFERENCES "BtpMetier"("id") ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE INDEX "BtpPrestation_metierId_idx" ON "BtpPrestation"("metierId");

INSERT INTO "BtpMetier" ("id", "label", "codeNaf", "sortOrder") VALUES
  ('plomberie', 'Plomberie & chauffage', '43.22A,43.22B', 0),
  ('electricite', 'Électricité (installations)', '43.21A', 1),
  ('maconnerie', 'Maçonnerie & gros œuvre', '43.99A', 2),
  ('menuiserie', 'Menuiserie, bois & PVC', '43.32A', 3),
  ('peinture', 'Peinture & vitrerie', '43.34Z', 4),
  ('carrelage', 'Carrelage & revêtements sols/murs', '43.33Z', 5),
  ('platrerie', 'Plâtrerie & plaques de plâtre', '43.31Z', 6),
  ('couverture', 'Couverture & étanchéité toiture', '43.91A,43.91B', 7),
  ('demolition', 'Démolition & terrassement', '43.11Z,43.12A,43.12B', 8),
  ('autres-btp', 'Autres travaux spécialisés BTP', '43.99C', 9);

INSERT INTO "BtpPrestation" ("id", "metierId", "label", "pricedBySurface", "sortOrder") VALUES
  ('sd-bain-complete', 'plomberie', 'Salle de bain complète (création / rénovation)', true, 0),
  ('douche-baignoire', 'plomberie', 'Douche, baignoire, receveur, paroi', false, 1),
  ('wc-suspendu-broyeur', 'plomberie', 'WC, WC suspendu, broyeur sanitaire', false, 2),
  ('evier-lave-vaisselle', 'plomberie', 'Évier cuisine, lave-vaisselle, raccordements', false, 3),
  ('robinetterie', 'plomberie', 'Robinetterie (remplacement, mitigeur, mélangeur)', false, 4),
  ('fuites-recherche', 'plomberie', 'Fuites — recherche et réparation', false, 5),
  ('canalisation-engorgee', 'plomberie', 'Canalisations engorgées / débouchage', false, 6),
  ('ballon-ecs', 'plomberie', 'Ballon d''eau chaude, cumulus, surcumulateur', false, 7),
  ('chauffage-emitters', 'plomberie', 'Radiateurs, sèche-serviettes, robinets thermostatiques', false, 8),
  ('plan-chauffage-pac', 'plomberie', 'Raccordements pompe à chaleur / plancher chauffant (hydraulique)', true, 9),
  ('adoucisseur-filtre', 'plomberie', 'Adoucisseur, filtration, traitement d''eau', false, 10),
  ('vmc-piquage', 'plomberie', 'Piquages VMC / extracteurs (eau usées liées à l''équipement)', false, 11),
  ('mise-normes-tableau', 'electricite', 'Mise aux normes du tableau électrique', false, 0),
  ('nouveau-tableau', 'electricite', 'Nouveau tableau / réagencement des circuits', false, 1),
  ('prises-interrupteurs', 'electricite', 'Prises, interrupteurs, points lumineux', false, 2),
  ('eclairage-encastre', 'electricite', 'Spots, rails, éclairage LED intérieur / extérieur', false, 3),
  ('depannage-pannes', 'electricite', 'Dépannage, recherche de panne', false, 4),
  ('installation-neuf', 'electricite', 'Installation neuve (logement, extension)', false, 5),
  ('renovation-secondaire', 'electricite', 'Rénovation tertiaire / locaux pros', false, 6),
  ('domotique', 'electricite', 'Domotique, volets roulants électriques, programmation', false, 7),
  ('borne-recharge', 'electricite', 'Borne de recharge véhicule électrique', false, 8),
  ('mise-terre-liaison', 'electricite', 'Mise à la terre, liaisons équipotentielles', false, 9),
  ('courant-faible', 'electricite', 'Courant faible (RJ45, antenne, interphone basique)', false, 10),
  ('extension-gros-oeuvre', 'maconnerie', 'Extension, surélévation — gros œuvre', true, 0),
  ('murs-clotures', 'maconnerie', 'Murs, clôtures, murets, soubassements', true, 1),
  ('ouvertures-baies', 'maconnerie', 'Ouverture / création de baies, linteaux', false, 2),
  ('dalle-chape', 'maconnerie', 'Dalle béton, chape', true, 3),
  ('terrasse-exterieure', 'maconnerie', 'Terrasse portée, plots, maçonnerie extérieure', true, 4),
  ('reprises-fissures', 'maconnerie', 'Reprises de fissures, scellements', false, 5),
  ('enduits-facade', 'maconnerie', 'Enduits façade / reprises maçonnage', true, 6),
  ('escaliers-beton', 'maconnerie', 'Escaliers béton, rampes d''accès', false, 7),
  ('fenetres-pvc-bois-alu', 'menuiserie', 'Fenêtres PVC, bois, alu — pose / remplacement', true, 0),
  ('portes-entree', 'menuiserie', 'Portes d''entrée, portes blindées', false, 1),
  ('portes-interieures', 'menuiserie', 'Portes intérieures, portes coulissantes', false, 2),
  ('volets', 'menuiserie', 'Volets roulants, battants, persiennes', false, 3),
  ('garde-corps', 'menuiserie', 'Garde-corps, tringles rideaux intégrées (menuiserie)', false, 4),
  ('cuisine-meuble', 'menuiserie', 'Pose cuisine équipée (meubles, plans de travail bois)', false, 5),
  ('placards-dressing', 'menuiserie', 'Placards, dressings sur mesure', true, 6),
  ('parquet-stratifie', 'menuiserie', 'Parquet, stratifié, lame PVC clipsée', true, 7),
  ('lambourdes-ossature-bois', 'menuiserie', 'Ossature bois légère, lambourdes (hors charpente lourde)', false, 8),
  ('peinture-interieure', 'peinture', 'Peinture intérieure murs / plafonds / boiseries', true, 0),
  ('peinture-facade', 'peinture', 'Peinture façade, ravalement léger', true, 1),
  ('vitrerie-simple', 'peinture', 'Vitrerie simple (petits carreaux, doubles vitrages accessibles)', true, 2),
  ('papier-peint-toile', 'peinture', 'Papier peint, toile de verre, revêtements muraux', true, 3),
  ('preparation-supports', 'peinture', 'Préparation des supports (rebouchage, ponçage)', true, 4),
  ('laques-batiments', 'peinture', 'Laques, peintures sols (locaux secs)', true, 5),
  ('carrelage-sdb', 'carrelage', 'Carrelage salle de bain, douche à l''italienne', true, 0),
  ('carrelage-cuisine', 'carrelage', 'Carrelage cuisine, crédence', true, 1),
  ('carrelage-sol-sejour', 'carrelage', 'Carrelage sol séjour, entrée, couloir', true, 2),
  ('carrelage-exterieur', 'carrelage', 'Carrelage / grès cérame extérieur, terrasse', true, 3),
  ('mosaique-faience', 'carrelage', 'Faïence, mosaïque, bordures', true, 4),
  ('chape-ragreage', 'carrelage', 'Chape, ragréage avant pose', true, 5),
  ('joints-hydrofuge', 'carrelage', 'Joints hydrofuges, traitement des angles', true, 6),
  ('cloisons-ba13', 'platrerie', 'Cloisons en plaques de plâtre (BA13)', true, 0),
  ('doublages-isolation', 'platrerie', 'Doublages collés / sur ossature + isolation', true, 1),
  ('faux-plafonds', 'platrerie', 'Faux plafonds suspendus, dalles acoustiques', true, 2),
  ('enduits-lisses', 'platrerie', 'Enduits lissés, bandes à joints', true, 3),
  ('trous-ouvertures', 'platrerie', 'Reprises après ouvertures, trous, saignées', true, 4),
  ('corniches-decor', 'platrerie', 'Corniches, éléments décoratifs plâtre / staff (léger)', true, 5),
  ('tuiles-ardoises', 'couverture', 'Tuiles, ardoises — pose et réparation', true, 0),
  ('etancheite-toiture', 'couverture', 'Étanchéité toiture-terrasse, relevés', true, 1),
  ('zinguerie', 'couverture', 'Zinguerie, gouttières, chéneaux, descentes', false, 2),
  ('velux-fenetres-toit', 'couverture', 'Fenêtres de toit, Velux — entourage', false, 3),
  ('isolation-combles', 'couverture', 'Isolation de combles (soufflage, rouleaux, panneaux)', true, 4),
  ('demoussage-hydrofuge', 'couverture', 'Démoussage, traitement hydrofuge toiture', true, 5),
  ('charpente-legere-reparation', 'couverture', 'Petites réparations charpente accessible (liteaux, voliges)', false, 6),
  ('demolition-maison', 'demolition', 'Démolition maison / bâtiment léger', true, 0),
  ('demolition-interieure', 'demolition', 'Dépose cloisons, sanitaires, cuisines', true, 1),
  ('terrassement-tranchee', 'demolition', 'Terrassement, tranchées, fouilles', true, 2),
  ('evacuation-dechets', 'demolition', 'Évacuation gravats, bennes, tri', false, 3),
  ('curage-locaux', 'demolition', 'Curage de locaux, débarras chantier', false, 4),
  ('sciage-carottage', 'demolition', 'Sciage, carottage (accès sous-traitance possible)', false, 5),
  ('second-oeuvre-divers', 'autres-btp', 'Second œuvre divers (pose accessoires, petits travaux)', false, 0),
  ('etancheite-sou-sol', 'autres-btp', 'Étanchéité sous-sol, cuvelage léger', true, 1),
  ('isolation-acoustique', 'autres-btp', 'Isolation acoustique ponctuelle (complément)', true, 2),
  ('nettoyage-haute-pression', 'autres-btp', 'Nettoyage façade / toiture haute pression', true, 3),
  ('autre-sur-devis', 'autres-btp', 'Autre — précisé au devis', false, 4);
